import Header from "@/components/Header"
import { dbSemestersGet } from "@/lib/db/semester"
import { cn } from "@/lib/utils"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { CourseProvider } from "@/components/CourseProvider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const semesters = await dbSemestersGet()
  return (
    <html lang="en">
      <body className={cn(inter.className, "flex flex-col h-screen select-none")}>
        <CourseProvider>
          <Header semesters={semesters} />
          <div className="overflow-x-scroll flex-1">{children}</div>
        </CourseProvider>
      </body>
    </html>
  )
}
